name: Publish to 📦 PyPI and 📦 TestPyPI

on:
  release:
    types: [created]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '1.8.3'

    - name: Build with poetry
      run: poetry build

    - name: Setup repositories for test pypi
      run: poetry config repositories.test-pypi https://test.pypi.org/legacy/

    - name: Set api token for test pypi
      run: poetry config pypi-token.test-pypi ${{secrets.TEST_PYPI_TOKEN}}

    - name: Set api token for  pypi
      run: poetry config pypi-token.pypi ${{secrets.PYPI_TOKEN}}

    - name: Publish to test instance of PyPi
      run: poetry publish -r test-pypi

    - name: Publish to PyPi
      run: poetry publish