name: Publish to 📦 PyPI and 📦 TestPyPI

on:
  release:
    types: [created]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Build sdist
      run: python setup.py sdist

    - uses: yaananth/twine-upload@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets.PYPI_TOKEN) }}